version: '3.7'
services:
    nginx:
        container_name: tripsit_web
        build: .
        restart: always
        ports:
            - 443:443/tcp
            - 80:80/tcp
        volumes:
            - ./web:/usr/share/nginx/beta.tripsit.me
            - ./config/nginx.conf:/etc/nginx/nginx.conf
            - ./config/sites:/etc/nginx/sites
